import { uiTokens } from './uiTokens.js'

export const dbanuStyles = {
  baseFont: {
    fontFamily: uiTokens.tipografia.familia,
    letterSpacing: 0,
  },
  field: {
    '& .MuiInputBase-root': {
      fontSize: 12,
      minHeight: 38,
      borderRadius: 0.5,
      bgcolor: 'background.paper',
    },
    '& .MuiInputLabel-root': {
      fontSize: 12,
    },
  },
  table: {
    '& th': {
      fontSize: 11,
      fontWeight: 900,
      color: 'text.primary',
      bgcolor: (theme) => theme.palette.mode === 'dark' ? '#273449' : uiTokens.colores.cabeceraTabla,
      borderBottom: 1,
      borderColor: 'divider',
      py: 0.9,
      whiteSpace: 'nowrap',
    },
    '& td': {
      fontSize: 12,
      borderBottom: 1,
      borderColor: 'divider',
      py: 0.8,
      verticalAlign: 'middle',
    },
    '& th:last-of-type, & td:last-of-type': {
      textAlign: 'center !important',
    },
    '& td:last-of-type > .MuiStack-root': {
      justifyContent: 'center !important',
    },
  },
  tablePaper: {
    border: 1,
    borderColor: 'divider',
    borderRadius: 0.5,
    overflow: 'hidden',
    bgcolor: 'background.paper',
    boxShadow: '0 12px 30px rgba(15, 58, 107, 0.08)',
  },
  actionEdit: {
    width: 28,
    height: 28,
    borderRadius: 0.5,
    border: `1px solid ${uiTokens.colores.acento}`,
    bgcolor: 'background.paper',
    color: uiTokens.colores.acento,
    mr: 0.75,
    '&:hover': { bgcolor: 'rgba(212, 160, 23, 0.08)', borderColor: uiTokens.colores.acento },
  },
  actionDelete: {
    width: 28,
    height: 28,
    borderRadius: 0.5,
    border: `1px solid ${uiTokens.colores.secundario} !important`,
    borderColor: `${uiTokens.colores.secundario} !important`,
    bgcolor: 'background.paper',
    color: `${uiTokens.colores.secundario} !important`,
    '& .MuiSvgIcon-root': {
      color: `${uiTokens.colores.secundario} !important`,
      fill: 'currentColor',
    },
    '&:hover': {
      bgcolor: `${uiTokens.colores.secundarioSuave} !important`,
      borderColor: `${uiTokens.colores.secundario} !important`,
      color: `${uiTokens.colores.secundarioOscuro} !important`,
      '& .MuiSvgIcon-root': {
        color: `${uiTokens.colores.secundarioOscuro} !important`,
      },
    },
  },
  actionView: {
    width: 28,
    height: 28,
    borderRadius: 0.5,
    border: `1px solid ${uiTokens.colores.primario}`,
    bgcolor: 'background.paper',
    color: uiTokens.colores.primario,
    mr: 0.75,
    '&:hover': { bgcolor: 'rgba(20, 73, 133, 0.08)', borderColor: uiTokens.colores.primario },
  },
  actionState: {
    width: 28,
    height: 28,
    borderRadius: 0.5,
    border: `1px solid ${uiTokens.colores.primario}`,
    bgcolor: 'background.paper',
    color: uiTokens.colores.primario,
    mr: 0.75,
    '&:hover': { bgcolor: 'rgba(20, 73, 133, 0.08)', borderColor: uiTokens.colores.primario },
  },
  addButton: {
    minHeight: 38,
    px: 1.7,
    bgcolor: uiTokens.colores.primario,
    color: '#fff',
    borderRadius: 0.5,
    textTransform: 'none',
    fontWeight: 900,
    boxShadow: '0 10px 20px rgba(20, 73, 133, 0.18)',
    '&:hover': { bgcolor: uiTokens.colores.primarioOscuro },
  },
  addButtonRevive: {
    minHeight: 38,
    px: 1.45,
    bgcolor: uiTokens.colores.acento,
    color: '#111827',
    border: `1px solid ${uiTokens.colores.acento}`,
    borderRadius: 0,
    textTransform: 'uppercase',
    fontWeight: 900,
    boxShadow: 'none',
    '& .MuiButton-startIcon': {
      width: 24,
      height: 24,
      mr: 1,
      ml: 0,
      display: 'grid',
      placeItems: 'center',
      borderRadius: 0.6,
      color: '#111827',
      bgcolor: 'rgba(255,255,255,0.34)',
    },
    '& .MuiButton-startIcon > *:nth-of-type(1)': {
      fontSize: 18,
    },
    '&:hover': {
      bgcolor: uiTokens.colores.acentoOscuro,
      borderColor: uiTokens.colores.acentoOscuro,
      boxShadow: '0 8px 18px rgba(184,136,15,0.14)',
    },
    '&.Mui-disabled': {
      borderColor: uiTokens.colores.borde,
      color: uiTokens.colores.textoMedio,
      bgcolor: '#f5f5f5',
      '& .MuiButton-startIcon': {
        bgcolor: uiTokens.colores.borde,
      },
    },
  },
  secondaryButtonRevive: {
    minHeight: 38,
    px: 1.35,
    bgcolor: 'background.paper',
    color: uiTokens.colores.textoFuerte,
    border: `1px solid ${uiTokens.colores.borde}`,
    borderRadius: 0.5,
    textTransform: 'none',
    fontWeight: 900,
    boxShadow: 'none',
    '& .MuiButton-startIcon': {
      mr: 0.8,
      color: uiTokens.colores.textoFuerte,
    },
    '& .MuiButton-startIcon > *:nth-of-type(1)': {
      fontSize: 18,
    },
    '&:hover': {
      bgcolor: uiTokens.colores.acentoSuave,
      borderColor: uiTokens.colores.acento,
      color: uiTokens.colores.acentoOscuro,
    },
  },
  backButton: {
    minHeight: 38,
    px: 1.7,
    borderRadius: 0.5,
    textTransform: 'none',
    fontWeight: 900,
    borderColor: uiTokens.colores.primario,
    color: uiTokens.colores.primario,
    '&:hover': { bgcolor: 'rgba(20, 73, 133, 0.08)', borderColor: uiTokens.colores.primarioOscuro },
  },
  cancelButton: {
    minHeight: 38,
    minWidth: 118,
    px: 1.8,
    borderRadius: 0.5,
    textTransform: 'none',
    fontWeight: 900,
    borderColor: uiTokens.colores.secundario,
    color: uiTokens.colores.secundario,
    bgcolor: 'background.paper',
    '&:hover': {
      bgcolor: uiTokens.colores.secundarioSuave,
      borderColor: uiTokens.colores.secundarioOscuro,
      color: uiTokens.colores.secundarioOscuro,
    },
  },
  saveButton: {
    minHeight: 38,
    minWidth: 118,
    px: 1.8,
    borderRadius: 0.5,
    textTransform: 'none',
    fontWeight: 900,
    borderColor: uiTokens.colores.exito,
    color: uiTokens.colores.exito,
    bgcolor: 'background.paper',
    '&:hover': {
      bgcolor: 'rgba(8, 127, 91, 0.08)',
      borderColor: uiTokens.colores.exito,
      color: uiTokens.colores.exito,
    },
  },
  formActions: {
    mt: 2,
    px: 2.5,
    pb: 2.5,
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 1.5,
  },
  dialogActions: {
    px: 2.5,
    py: 1.6,
    justifyContent: 'flex-end',
    gap: 1.2,
    bgcolor: 'background.paper',
  },
}
